### ISSUE TITLE
inconsistent link to COS directory for model files

### ISSUE THREAD

**Issue by vabarbosa** [IBM/MAX-Sports-Video-Classifier#15]
the [README](https://github.com/IBM/MAX-Sports-Video-Classifier/blob/master/README.md) contains this link to the model files:

- http://max-assets.s3-api.us-geo.objectstorage.softlayer.net/tf/c3d/max_c3d_sports1m_tf.tar.gz

this works. however, it is different than the link in the [Dockerfile](https://github.com/IBM/MAX-Sports-Video-Classifier/blob/master/Dockerfile):

- http://max-assets.s3-api.us-geo.objectstorage.softlayer.net/sports-video-classifier/1.0/assets.tar.gz

i would expect both of these to point to the same set of model files.
in addition, both of the links should be pointing to the new US cross region:

`s3.us.cloud-object-storage.appdomain.cloud`

because the old one has been deprecated:

~~`s3-api.us-geo.objectstorage.softlayer.net`~~

**Comment by gdequeiroz** [comment]
I think this was solved via #26. (cc @djalova @vabarbosa)

**Comment by djalova** [comment]
Thanks for catching @gdequeiroz 
Closing this issue.
